### PR TITLE
Add commit history [Issue 549]

### PR DESCRIPTION
**Pull request by dawidwoz**
image
The pull request to issue [issue 549](https://github.com/git-truck/git-truck/issues/549).

### CODE REVIEW

**Comment by dawidwoz** [comment]
@mircealungu Can you, please, have a look if it is what you wanted to have in the product? (I cannot add reviewers)

**Comment by mircealungu** [comment]
> @mircealungu Can you, please, have a look if it is what you wanted to have in the product? (I cannot add reviewers)

@joglr @emiljapelt - can one of you folks have a look at this? you know the code better than i do...

**Comment by tjomson** [comment]
Awesome job! I tried to get get this working, but had trouble with, so cool that you could :)

It seems that it impacts analysis-time quite a lot. I think we should either get the history on demand (by having a button on the Details-panel), or load the commits during the hydration.

I am leaning to the former. Tge latter probably requires a new data structure for commits, and still impacts analysis-time somewhat.

What do you think?

**Comment by dawidwoz** [comment]
@tjomson Can you, please, explain what was the trouble to test it?

It's true it impacts analysis-time. The impact depends on the number of commits in the repository.  The strategy to implement this change should be aligned with another issue: [Issue 595: Scalability](https://github.com/git-truck/git-truck/issues/595) then I'm happy to rewrite the logic of how it's done.  

It's okay for me to wait until the scalability strategy is there to add this feature.

**Comment by joglr** [comment]
> @tjomson Can you, please, explain what was the trouble to test it?

I think he meant that he tried to implement this functionality, but that he is glad you managed to implement it!

> It's true it impacts analysis-time. The impact depends on the number of commits in the repository. The strategy to implement this change should be aligned with another issue: [Issue 595: Scalability](https://github.com/git-truck/git-truck/issues/595) then I'm happy to rewrite the logic of how it's done.

I have experimented a bit with loading the data on demand, but I think this is a really nice feature to land for now, so I say we should get this merged soon. There are some console.log's that should be removed. I will review the code in a few days when I get the time.

> It's okay for me to wait until the scalability strategy is there to add this feature.

**Comment by dawidwoz** [comment]
@joglr that's great. I'm doing some experiments of asynchronous loading in the background and on demand over the weekend if I manage to have a demo, I'll share it here :)

**Comment by tjomson** [comment]
> @joglr that's great. I'm doing some experiments of asynchronous loading in the background and on demand over the weekend if I manage to have a demo, I'll share it here :)

I got a version of on-demand loading working. I will try to put it into the pretty UI you have made, then we can compare :)

**Comment by tjomson** [comment]
See #606

**Comment by tjomson** [comment]
Okay, I made a version that loads commit history during hydration, and which does not impact the analysis-time. I think that is pretty nice :D
#607

**Comment by dawidwoz** [comment]
@tjomson I've checked on _vscode_ and your version is even faster than the current master 🙂 Good job! 🥇 

I'll close this PR as your solution is better. 

On current master:
master_vscode
With #607:
pr606_vscode

However, I've been working in a slightly different direction.  My aim is a situation where you load the visualisation very quickly and then do all analysis and hydration in the background through workers. It's not done yet. Now workers don't work but I'm going towards this solution in #608. Current time for vscode is as below:

image

Now, I'm fighting with workers but it seems promising to be finalized quickly 🤞

**Pull request closed without merging**
