### PR TITLE
Usage improvements

### LINKED ISSUE #290: Convert scripts to npm scripts

### LINKED ISSUE #327: Update documentation

### LINKED ISSUE #333: parser --out doesn't handle absolute path
```
~/repo/git-truck/parser$ npm start -- --path ~/repo/bong-maps/ --out ~/data.json

> parser@1.0.0 start
> npm run build && node ./dist "--path" "/home/hojelse/repo/bong-maps/" "--out" "/home/hojelse/data.json"


> parser@1.0.0 build
> tsc

✔ Found branch head [6ms]
✔ Commit tree parsed [379ms]
✔ Commit tree hydrated [3.23s]
✔ Wrote data to /home/hojelse/repo/git-truck/parser/home/hojelse/data.json [2ms]
```

### LINKED ISSUE #334: Pass arguments to parser instead of frontend

### PR DESCRIPTION
**Pull request by joglr**
- [x] Resolves #334 (by @hojelse)
- [x] Fixes #333 (by @hojelse)
- [x] Fixes #327 
- [x] Fixes #290

### CODE REVIEW

**Review by tjomson — CHANGES_REQUESTED** [review]
The arguments to the CLI don't work
For example 
> npm start -- --path ../bong-maps --branch main

does not run on the main branch of bong-maps. It runs on the currently checked out branch of git-truck

This is also the case with npm run dev

**Comment by tjomson** [comment]
The 3 step guide in the readme seems like it could just be
> npm start

because that also runs npm install

**Comment by hojelse** [comment]
I've tried addressing the issue above in #335

**Review by tjomson — APPROVED** [review]
Works on my laptop, but not my desktop. Let's merge it. My desktop probably had something configured incorrectly

**Pull request merged**
