### PR TITLE
Fix closing regexp for PGP signatures

### PR DESCRIPTION
**Pull request by epkanol**
Allow gpgsig to be closed by -----END SIGNED MESSAGE----- as well as the old END PGP SIGNATURE

### CODE REVIEW

**Comment by epkanol** [comment]
Some of my git repos closes the gpg signature with the tag
-----END SIGNED MESSAGE-----
When analysing these repos with git-truck, the analyser just hangs, waiting for the PGP SIGNATURE
This patch allows either of these tags to close off the signature and let the analysis go on.
I'm not that well-versed in Node.js, so I didn't dare to write a unit test for this small change.

**Comment by joglr** [comment]
Hello! Thank you for your contribution. 

@tjomson Can you take a look at this? I think this is your area of expertise.

**Review by tjomson — CHANGES_REQUESTED** [review]
Hi, thanks for your input!
Could you please make the group (PGP SIGNATURE|SIGNED MESSAGE) non-capturing?
Then I will approve it :)

**Comment by epkanol** [comment]
Updated (via force-pushing to my own fork, I hope this settles things in this PR - seems to be working allright...)

**Comment by joglr** [comment]
I will publish an experimental release to quickly test, then I will also approve.

**Review by joglr — CHANGES_REQUESTED** [review]
Will test, and then approve

**Review by joglr — APPROVED** [review]

**Comment by joglr** [comment]
https://github.com/git-truck/git-truck/releases/tag/v1.4.3

**Pull request merged**
