### PR TITLE
Add color legend in author distribution

### LINKED ISSUE #585: Color Legend Near Author distribution
Color Legend Near Author distribution would make my life easier :) 
Please describe your idea / problem below:
image

### PR DESCRIPTION
**Pull request by joglr**
Fixes #585

This test has been published as `git-truck@0.0.0-1482796`

### CODE REVIEW

**Comment by joglr** [comment]
@mircealungu 
Not sure if I like this change or not
image

**Comment by mircealungu** [comment]
see my comment in: https://github.com/git-truck/git-truck/issues/585

**Comment by joglr** [comment]
> If it's not "ugly" to only make it visible in the top-contributor view that would be an option. 

@mircealungu I have addressed this and published a new experimental release. I think we could merge this, I think it's pretty nice and we have also talked about doing this for a long time.

Try it out!: git-truck@0.0.0-1482796

**Comment by mircealungu** [comment]
I like it :) 

image

Two questions that I've realized I have when looking at it are:
- why is there "13 more" in the legend and "448 more" in the detail panel?

**Comment by joglr** [comment]
> I like it :)
> 
> image
> 
> Two questions that I've realized I have when looking at it are:
> 
> * why is there "13 more" in the legend and "448 more" in the detail panel?

The Legend only shows people who are top contributor to at least one file, while the author distribution shows everyone who have made edits in the selected file / folder. Does that make sense?

**Comment by mircealungu** [comment]
ah! makes a lot of sense. thanks for the clarification Jonas!

**Pull request merged**
