### PR TITLE
Add opening file

### LINKED ISSUE #258: Support for opening files from Details pane
image
Clicking the path of a file should open it

### PR DESCRIPTION
**Pull request by tjomson**
resolves #258

### CODE REVIEW

**Review by joglr — APPROVED** [review]
It works on my machine! 👨🏼‍💻🤖

**Review by joglr — DISMISSED** [review]
Would it be possible to show the user an error if the file fails to open?

**Comment by tjomson** [comment]
> Would it be possible to show the user an error if the file fails to open?

Windows shows an error when it can't open. Also, i have added a log.debug print. We don't have a good way to show errors in UI, so i think we should look into that in #432

**Review by emiljapelt — APPROVED** [review]
yay, works for me :rock:

**Pull request merged**
