### PR TITLE
Find min and max commit numbers during rendering

### LINKED ISSUE #588: adapting the color scale after removing outlier
looking at number of commits in sqlite, i see that the manifest file has 22K commits. 
so i filter it out. 
however, the range does not adjust.
shouldn't it? 

image

### PR DESCRIPTION
**Pull request by emiljapelt**
Resolves #588

### CODE REVIEW

**Comment by joglr** [comment]
I have released this experimental release that you can try out to test this fix: git-truck@0.0.0-3e8160c6

**Comment by mircealungu** [comment]
As far as I can see it still does not work for sqlite? I've filtered out the outlier, but the scale is still the same. 
image

**Comment by joglr** [comment]
Thomas think you might need glasses 😅

 I tried it out and it looks their are two files with this amount of commits. One of them is 64 bytes, so it is hard to see, but if you hide that as well it works as intended. This speaks to implementing a selectable range instead or some sort of outlier detection

image

**Comment by mircealungu** [comment]
> On 23 Sep 2022, at 14.17, Jonas Røssum ***@***.***> wrote:
> 
> 
> Thomas think you might need glasses 😅
> 
> 
HE SAW THAT?!

> I tried it out and it looks their are two files with this amount of commits. One of them is 64 bytes, so it is hard to see, but if you hide that as well it works as intended. This speaks to implementing a selectable range instead or some sort of outlier detection
> 
> 

Indeed, a much better solutiono for people who don’t have super-human retinas :)



>  <https://user-images.githubusercontent.com/1959615/191958333-166d3d09-0281-4de4-9349-75623dff8ce2.png>
> —
> 

Look at that beautiful vis! 

I like it.

M.

**Review by joglr — APPROVED** [review]
Nice work, LGTM!

**Pull request merged**
